on: push

name: Test Transition Issue

jobs:
  build:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo "$secrets.JIRA_BASE_URL ${{ secrets.JIRA_BASE_URL }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
